### ISSUE TITLE
スマホサイズでアクセスした時に白い画面が表示される

### ISSUE THREAD

**Issue by Hirochon** [fujiya228/fujiya228-com-2020-12-28#36]
## 概要
ブラウザ関係なく、画面サイズを絞った状態で訪れると、画面が真っ白。

### 詳細
まるでアタックで洗濯した後みたい！

![スクリーンショット 2021-06-04 22 36 59](https://user-images.githubusercontent.com/50178851/120810261-d3394480-c585-11eb-8982-e3b0d72d216f.png)

**Comment by fujiya228** [comment]
まじか、、、

原因まで突き止めてくれるとありがたいな

**Comment by Hirochon** [comment]
アドセンス！！！！！！！！

**Comment by Hirochon** [comment]
250px!

**Comment by fujiya228** [comment]
@Hirochon 
エラーは消えて無いんですけど多分解決したんで確認お願いします！

**Comment by Hirochon** [comment]
@fujiya228 
ページが見れる！！！とても良いと思います！！！
